[project]
name = "module-3-template"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "langchain-text-splitters>=1.1.0",
    "openai>=2.20.0",
    "pandas>=3.0.0",
    "pydantic>=2.12.5",
    "pymupdf>=1.27.1",
]
